set nocompatible
let mapleader="," 
set runtimepath^=~/.config/vim
set runtimepath+=~/.config/vim/after

source ~/.config/vim/netrw.vim
source ~/.config/vim/options.vim
source ~/.config/vim/keymaps.vim

filetype plugin indent on
syntax on
