name: "checks"

on:
  pull_request:
  push:
    branches: 
      - "main"
    paths:
      - "**.nix"
      - "flake.lock"
      - ".github/workflows/checks.yml"

permissions:
  id-token: "write"
  contents: "read"

jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: DeterminateSystems/flake-checker-action@9ee1c5473f1abdfb299f6c4f0fab813147c97fe3 # main
        with:
          fail-mode: true
      - uses: DeterminateSystems/determinate-nix-action@9adf02b41cfdac2632e1c16f0480ff5bf3b05dd6 # v3
      - uses: DeterminateSystems/magic-nix-cache-action@14645543c3b214bedad3b9b49775cb042f4c1fc7 # main
      - name: Run nix flake check
        run: nix flake check
